name: build

on:
  push:
    branches: [ "ci" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      id: build
      run:  ./build.sh
    
    - uses: actions/upload-artifact@v4
      if: ${{ failure() && steps.build.outcome == 'failure' }}
      with:
        name: build-log
        path: |
          ./Vendor/*.log
    
    - name: package
      run:  ./xcframework.sh && tar -czf Framework.tgz Framework

    - uses: actions/upload-artifact@v4
      with:
        name: libnfs-frameworks.tgz
        path: Framework.tgz
